
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: flaggers.operator.alauda.io
spec:
  group: operator.alauda.io
  names:
    kind: Flagger
    listKind: FlaggerList
    plural: flaggers
    singular: flagger
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Flagger is the Schema for the flaggers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FlaggerSpec defines the desired state of Flagger
          properties:
            cluster:
              description: Foo is an example field of Flagger. Edit Flagger_types.go
                to remove/update Foo string `json:"foo,omitempty"`
              type: string
            namespace:
              type: string
            parameters:
              additionalProperties:
                type: object
              type: object
          required:
          - cluster
          type: object
        status:
          description: FlaggerStatus defines the observed state of Flagger
          properties:
            deleteConditions:
              additionalProperties:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    name:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - name
                  - reason
                  - status
                  type: object
                type: array
              type: object
            installConditions:
              additionalProperties:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    name:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - name
                  - reason
                  - status
                  type: object
                type: array
              type: object
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
